openapi: 3.1.0
info:
  title: TG Content & SEO API
  description: API to fetch Google Search Console data for GPT content generation.
  version: 1.0.0

servers:
  - url: https://my-plugin-api-gsc.onrender.com

paths:

  /seo/top_keywords:
    get:
      operationId: getTopKeywords
      summary: Get top-performing keywords
      description: Returns top-performing keywords from Google Search Console.
      security:
        - OAuth2Google:
            - "https://www.googleapis.com/auth/webmasters.readonly"
      responses:
        "200":
          description: Top keywords fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  keywords:
                    type: array
                    items:
                      type: string
      x-openai-action:
        operationId: getTopKeywords

  /seo/top_pages:
    get:
      operationId: getTopPages
      summary: Get top-performing pages
      description: Returns top-performing pages from Google Search Console.
      security:
        - OAuth2Google:
            - "https://www.googleapis.com/auth/webmasters.readonly"
      responses:
        "200":
          description: Top pages fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  pages:
                    type: array
                    items:
                      type: string
      x-openai-action:
        operationId: getTopPages

  /seo/low_ctr_queries:
    get:
      operationId: getLowCTRQueries
      summary: Get queries with low CTR
      description: Returns queries with high impressions but low click-through rates from Google Search Console.
      security:
        - OAuth2Google:
            - "https://www.googleapis.com/auth/webmasters.readonly"
      responses:
        "200":
          description: Low CTR queries fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  queries:
                    type: array
                    items:
                      type: string
      x-openai-action:
        operationId: getLowCTRQueries

components:
  securitySchemes:
    OAuth2Google:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            "https://www.googleapis.com/auth/webmasters.readonly": "Read access to Google Search Console data"
  schemas: {}
